#### COMBINE CROSS-PARAMETER & PHQ9 RELATIONSHIP PLOTS INTO MULTI-PAGE PDF ####

pdf(file.path(output_dir, "parameter_relationships_summary.pdf"), width = 10, height = 8)
print(p_u_vs_tau_time1)
print(p_u_vs_tau_time2)
print(p_u_vs_beta_time1)
print(p_u_vs_beta_time2)
print(p_beta_vs_tau_time1)
print(p_beta_vs_tau_time2)
print(p_phq9_sum_vs_utility)
print(p_phq9_sum_vs_beta)
print(p_phq9_sum_vs_tau)
print(p_phq9_sd_vs_utility)
print(p_phq9_sd_vs_beta)
print(p_phq9_sd_vs_tau)
print(p_utility_vs_phq9_item)
print(p_mean_utility_vs_phq9_item)
dev.off()
