#### COMBINE TEST-RETEST PLOTS INTO MULTI-PAGE PDF ####

pdf(file.path(output_dir, "test_retest_summary.pdf"), width = 10, height = 8)
print(p_utility_retest)
print(p_tau_retest)
print(p_beta_retest)
print(p_key_decay_retest)
print(p_rho_retest)
print(p_phq9_sum_retest)
print(p_phq9_1_retest)
print(p_phq9_2_retest)
print(p_phq9_3_retest)
print(p_phq9_4_retest)
print(p_phq9_5_retest)
print(p_phq9_6_retest)
print(p_phq9_7_retest)
print(p_phq9_8_retest)
print(p_phq9_9_retest)
dev.off()
